---
- name: "Facts print the distribution"
  debug:
    msg: "{{ansible_distribution}}"

- name: " Package update if CentOS linux"
  yum:
    update_only: yes
    state: latest
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - update
    - centos

- name: " Installation of docker packages for CentOS linux"
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - packages
    - centos
    - docker
