---
- name: "Facts print the distribution"
  debug:
    msg: "{{ansible_distribution}}"

- name: " {{ tittle }} / Package update if {{ ansible_distribution }} linux"
  apt:
    force_apt_get: yes
    update_cache: yes
    only_upgrade: yes
    state: latest
  when: ansible_facts['distribution'] == "Debian"
  tags:
    - install
    - update
    - debian

- name: " {{ tittle }} / Remove old Installation of docker packages for {{ ansible_distribution }} linux"
  apt:
    force_apt_get: true
    autoremove: true
    purge: true
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_facts['distribution'] == "Debian"
  tags:
    - delete
    - debian
    - docker

- name: " {{  tittle }} / Installation of docker packages for {{ ansible_distribution }} linux"
  apt:
    force_apt_get: yes
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_facts['distribution'] == "Debian"
  tags:
    - install
    - debian
    - docker
