---
- name: "Facts print the distribution"
  debug:
    msg: "{{ansible_distribution}}"

- name: " Package update if Debian linux"
  apt:
    force_apt_get: yes
    update_cache: yes
    only_upgrade: yes
    state: latest
  when: ansible_facts['distribution'] == "Debian"
  tags:
    - update
    - debian

- name: " Remove old Installation of docker packages for Debian linux"
  apt:
    force_apt_get: true
    autoremove: true
    purge: true
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_facts['distribution'] == "Debian"
  tags:
    - remove
    - debian
    - docker

- name: " Installation of docker packages for Debian linux"
  apt:
    force_apt_get: yes
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_facts['distribution'] == "Debian"
  tags:
    - packages
    - debian
    - docker
