---
# tasks file for update_os

- name: " CENTOS / Call Package update for CentOs"
  vars:
    tittle: "CENTOS"
  include_tasks:
    file: centos.yaml 
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - update
    - install
    - centos

- name: " DEBIAN / Call Package update for debian"
  vars:
    tittle: "DEBIAN"
  include_tasks:
    file: debian.yaml 
  when: ansible_facts['distribution'] == "Debian"
  tags:
    - update
    - install
    - debian

