---
# tasks file for update_os
- name: "print a message to show if the call of the role is correct"
  debug:
    msg: "The role is called"

- name: " Call Package update for CentOs"
  include_tasks:
    file: centos.yaml 
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - update
    - centos

- name: " Call Package update for debian"
  include_tasks:
    file: debian.yaml 
  when: ansible_facts['distribution'] == "Debian"
  tags:
    - update
    - debian

