---
# tasks file for install_docker
- name: "Print a message to show the correct call of install_docker for CentOS"
  debug:
    msg: " The role install_docker is called"

- name: "Call installation module for CentOS"
  vars:
    install: "yes"
  include_tasks:
    file: docker_centos.yaml
  when: ansible_facts['distribution'] == "CentOS"

