---
# tasks file for install_docker
- name: "CENTOS / Call installation module for {{ ansible_distribution }}"
  vars:
    tittle: "CENTOS DOCKER"
    #install: "yes"
  include_tasks:
    file: docker_centos.yaml
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - centos
    - install
    - delete

- name: "DEBIAN / Call installation module for {{ ansible_distribution }}"
  vars:
    tittle: "DEBIAN DOCKER"
    #install: "yes"
  include_tasks:
    file: docker_debian.yaml
  when: ansible_facts['distribution'] == "Debian"
  tags:
    - debian
    - install
    - delete
