---
# Tasks file for kube_install
# When CENTOS server

- name: "Modify firewall rules for MASTER"
  firewalld:
    permanent: yes
    state: enabled
    port: "{{ item }}" 
  loop:
      - 179/tcp
      - 443/tcp
      - 2379/tcp
      - 2380/tcp
      - 5473/tcp
      - 6443/tcp
      - 10250/tcp
      - 10251/tcp
      - 10252/tcp
  when: ansible_facts['hostname'] == "haproxy"

- name: "Modify firewall rules for WORKER"
  firewalld:
    permanent: yes
    state: enabled
    port: "{{ item }}" 
  loop:
    - 179/tcp
    - 443/tcp
    - 5473/tcp
    - 10250/tcp
    - 30000-32767/tcp
  when: ansible_facts['hostname'] != "haproxy"

- name: "Reload firewall"
  command: firewall-cmd --reload

- name: "Add the repository to install kubernetes"
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repo
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-e17-x86_64"
    enabled: true
    gpgcheck: true
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-packages-key.gpg"
    repo_gpgcheck: true
    exclude: kube*
  tags:
    - repository
   
- name: "Désactiver la sécurité linux SELINUX"
  shell:
    cmd: "setenforce 0"
  args:
    executable: /bin/bash

- name: "Modifier le fichier /etc/selinux/config"
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing$'
    line: 'SELINUX=disabled'

- name: "Désactiver le swap pour que Kubernetes fonctionne"
  command: swapoff -a

- name: "Modifier le fichier /etc/fstab pour désactiver le swap"
  replace:
    path: /home/ansible/test
    regexp: '^([^#].*?\sswap\s+swap\s+.*)'
    replace: '# \g<1>'

 
